-- V30__create_n5_beginner_course.sql

INSERT INTO courses (id, name, name_jp, description, level, icon) 
VALUES ('n5_beginner', 'N5 - Nhập Môn', 'N5入門', 'Khóa học dành cho người mới bắt đầu: Bảng chữ cái và giới thiệu tiếng Nhật.', 'N5', '🌸');

-- Insert Lessons
INSERT INTO lessons (id, course_id, title, title_jp, category, level, content) VALUES
(1001, 'n5_beginner', 'Giới thiệu Tiếng Nhật', '日本語について', 'Ngữ pháp', 'N5', 'Bài học tổng quan về tiếng Nhật, bao gồm 3 hệ thống chữ viết: Hiragana, Katakana và Kanji, cùng với cách phát âm và cấu trúc câu cơ bản.'),
(1002, 'n5_beginner', 'Bảng chữ cái Hiragana (Bảng mềm)', 'ひらがな', 'Từ vựng', 'N5', 'Bảng chữ cái mềm Hiragana gồm 46 chữ cái cơ bản và các biến âm.'),
(1003, 'n5_beginner', 'Bảng chữ cái Katakana (Bảng cứng)', 'カタカナ', 'Từ vựng', 'N5', 'Bảng chữ cái cứng Katakana dùng để viết từ mượn tiếng nước ngoài.');

-- Insert Hiragana
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'あ', 'a', 'đọc như "a" trong tiếng Việt');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'い', 'i', 'đọc như "i" trong tiếng Việt');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'う', 'u', 'đọc như "ư" (hơi giống "u")');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'え', 'e', 'đọc như "ê" trong tiếng Việt');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'お', 'o', 'đọc như "ô" trong tiếng Việt');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'か', 'ka', 'đọc như "ca"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'き', 'ki', 'đọc như "ki"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'く', 'ku', 'đọc như "cư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'け', 'ke', 'đọc như "kê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'こ', 'ko', 'đọc như "cô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'さ', 'sa', 'đọc như "sa"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'し', 'shi', 'đọc gần giống "si" (hơi ngả sang shi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'す', 'su', 'đọc như "sư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'せ', 'se', 'đọc như "sê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'そ', 'so', 'đọc như "sô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'た', 'ta', 'đọc như "ta"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ち', 'chi', 'đọc như "chi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'つ', 'tsu', 'đọc gần giống "chư" (nhẹ)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'て', 'te', 'đọc như "tê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'と', 'to', 'đọc như "tô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'な', 'na', 'đọc như "na"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'に', 'ni', 'đọc như "ni"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぬ', 'nu', 'đọc như "nư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ね', 'ne', 'đọc như "nê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'の', 'no', 'đọc như "nô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'は', 'ha', 'đọc như "ha"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ひ', 'hi', 'đọc như "hi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ふ', 'fu', 'đọc như "phư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'へ', 'he', 'đọc như "hê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ほ', 'ho', 'đọc như "hô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ま', 'ma', 'đọc như "ma"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'み', 'mi', 'đọc như "mi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'む', 'mu', 'đọc như "mư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'め', 'me', 'đọc như "mê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'も', 'mo', 'đọc như "mô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'や', 'ya', 'đọc như "ya" (ia)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ゆ', 'yu', 'đọc như "yu" (iu)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'よ', 'yo', 'đọc như "yo" (iô)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ら', 'ra', 'đọc như "ra"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'り', 'ri', 'đọc như "ri"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'る', 'ru', 'đọc như "rư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'れ', 're', 'đọc như "rê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ろ', 'ro', 'đọc như "rô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'わ', 'wa', 'đọc như "wa" (oa)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'を', 'wo', 'đọc như "ô" (trợ từ)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ん', 'n', 'đọc như âm mũi "n" (hoặc m, ng)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'が', 'ga', 'đọc như "ga"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぎ', 'gi', 'đọc như "gi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぐ', 'gu', 'đọc như "gư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'げ', 'ge', 'đọc như "gê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ご', 'go', 'đọc như "gô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ざ', 'za', 'đọc như "da"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'じ', 'ji', 'đọc như "di"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ず', 'zu', 'đọc như "dư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぜ', 'ze', 'đọc như "dê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぞ', 'zo', 'đọc như "dô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'だ', 'da', 'đọc như "đa"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぢ', 'ji', 'đọc như "di"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'づ', 'zu', 'đọc như "dư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'で', 'de', 'đọc như "đê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ど', 'do', 'đọc như "đô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ば', 'ba', 'đọc như "ba"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'び', 'bi', 'đọc như "bi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぶ', 'bu', 'đọc như "bư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'べ', 'be', 'đọc như "bê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぼ', 'bo', 'đọc như "bô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぱ', 'pa', 'đọc như "pa" (bật hơi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぴ', 'pi', 'đọc như "pi" (bật hơi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぷ', 'pu', 'đọc như "pư" (bật hơi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぺ', 'pe', 'đọc như "pê" (bật hơi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1002, 'ぽ', 'po', 'đọc như "pô" (bật hơi)');

-- Insert Katakana
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ア', 'a', 'đọc như "a" trong tiếng Việt');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'イ', 'i', 'đọc như "i" trong tiếng Việt');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ウ', 'u', 'đọc như "ư" (hơi giống "u")');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'エ', 'e', 'đọc như "ê" trong tiếng Việt');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'オ', 'o', 'đọc như "ô" trong tiếng Việt');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'カ', 'ka', 'đọc như "ca"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'キ', 'ki', 'đọc như "ki"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ク', 'ku', 'đọc như "cư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ケ', 'ke', 'đọc như "kê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'コ', 'ko', 'đọc như "cô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'サ', 'sa', 'đọc như "sa"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'シ', 'shi', 'đọc gần giống "si" (hơi ngả sang shi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ス', 'su', 'đọc như "sư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'セ', 'se', 'đọc như "sê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ソ', 'so', 'đọc như "sô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'タ', 'ta', 'đọc như "ta"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'チ', 'chi', 'đọc như "chi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ツ', 'tsu', 'đọc gần giống "chư" (nhẹ)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'テ', 'te', 'đọc như "tê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ト', 'to', 'đọc như "tô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ナ', 'na', 'đọc như "na"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ニ', 'ni', 'đọc như "ni"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ヌ', 'nu', 'đọc như "nư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ネ', 'ne', 'đọc như "nê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ノ', 'no', 'đọc như "nô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ハ', 'ha', 'đọc như "ha"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ヒ', 'hi', 'đọc như "hi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'フ', 'fu', 'đọc như "phư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ヘ', 'he', 'đọc như "hê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ホ', 'ho', 'đọc như "hô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'マ', 'ma', 'đọc như "ma"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ミ', 'mi', 'đọc như "mi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ム', 'mu', 'đọc như "mư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'メ', 'me', 'đọc như "mê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'モ', 'mo', 'đọc như "mô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ヤ', 'ya', 'đọc như "ya" (ia)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ユ', 'yu', 'đọc như "yu" (iu)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ヨ', 'yo', 'đọc như "yo" (iô)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ラ', 'ra', 'đọc như "ra"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'リ', 'ri', 'đọc như "ri"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ル', 'ru', 'đọc như "rư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'レ', 're', 'đọc như "rê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ロ', 'ro', 'đọc như "rô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ワ', 'wa', 'đọc như "wa" (oa)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ヲ', 'wo', 'đọc như "ô" (trợ từ)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ン', 'n', 'đọc như âm mũi "n" (hoặc m, ng)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ガ', 'ga', 'đọc như "ga"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ギ', 'gi', 'đọc như "gi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'グ', 'gu', 'đọc như "gư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ゲ', 'ge', 'đọc như "gê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ゴ', 'go', 'đọc như "gô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ザ', 'za', 'đọc như "da"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ジ', 'ji', 'đọc như "di"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ズ', 'zu', 'đọc như "dư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ゼ', 'ze', 'đọc như "dê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ゾ', 'zo', 'đọc như "dô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ダ', 'da', 'đọc như "đa"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ヂ', 'ji', 'đọc như "di"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ヅ', 'zu', 'đọc như "dư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'デ', 'de', 'đọc như "đê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ド', 'do', 'đọc như "đô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'バ', 'ba', 'đọc như "ba"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ビ', 'bi', 'đọc như "bi"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ブ', 'bu', 'đọc như "bư"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ベ', 'be', 'đọc như "bê"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ボ', 'bo', 'đọc như "bô"');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'パ', 'pa', 'đọc như "pa" (bật hơi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ピ', 'pi', 'đọc như "pi" (bật hơi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'プ', 'pu', 'đọc như "pư" (bật hơi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ペ', 'pe', 'đọc như "pê" (bật hơi)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (1003, 'ポ', 'po', 'đọc như "pô" (bật hơi)');
