-- V36__add_missing_jpd316_vocab.sql

INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '様子', 'ようす', 'tình trạng, dáng vẻ');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '寄る', 'よる', 'ghé qua');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '展示', 'てんじ', 'trưng bày');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '気軽', 'きがる', 'thoải mái');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '偶然', 'ぐうぜん', 'tình cờ');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '突然', 'とつぜん', 'đột nhiên');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '急用', 'きゅうよう', 'việc gấp');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'ギャラリ', '', 'phòng trưng bày');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '座る', 'すわる', 'ngồi');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '窓', 'まど', 'cửa sổ');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '途中', 'とちゅう', 'giữa chừng');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '緑', 'みどり', 'xanh lá');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '雰囲気', 'ふんいき', 'bầu không khí');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '暖かい', '', 'ấm áp');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '目標', 'もくひょう', 'mục tiêu');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '雑巾', 'ぞうきん', 'giẻ lau');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'はり', '', 'kim, kim nhọn');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'そお', '', 'tầng/ thớ/ cỏ');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '16/02/26', '', '');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '横断', 'おうだん', 'băng qua');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '決して〜ないtuyệt đối không', '', '');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'いざという khi cần thiết/ khẩn cấp', '', '');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '故障するーこしょうするhỏng', 'máy móc', '');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '吹くーふくthổi', 'gió', '');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '19/03/26', '', '');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '滑る落ちる', 'すべりおちる', 'trượt xuống');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '元', 'もと', 'gốc, ban đầu');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '弁当箱', 'べんとうばこ', 'hộp cơm');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '傷', 'きず', 'vết thương');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '帽子', 'ぼうし', 'nón');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '怖い', 'こわい', 'đáng sợ');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '十分', 'じゅうぶん', 'đủ, đầy đủ, hoàn toàn');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '受け入れる', 'うけいれる', 'tiếp nhận');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '全国', 'ぜんこく', 'toàn quốc');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '仮説', 'かせつ', 'giả thuyết');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '張る', 'はる', 'căng, dán, giăng');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '引っ張る', 'ひっぱる', 'kéo, lôi');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '出張', 'しゅっちょう', 'đi công tác');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '数日', 'すうじつ', 'vài ngày');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '生活を送る', '', 'sinh hoạt');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '簡易便器', 'かんいべんき', 'bồn cầu đơn giản');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '安易', 'あんい', 'dễ dãi, đơn giản hoá');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '載せる', 'のせる', 'đăng lên(mạng)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'ふた', '', 'cái nắp');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'かまど', '', 'bếp lò');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'ポンプ', '', 'máy bơm');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'ベンチ', '', 'ghế băng(công viên)');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'ムンホ', 'ル', 'nắp cống');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '組み上げる', 'くみあげる', 'lắp ráp, xây dựng');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '用水', 'ようすい', 'nước dùng');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '防火', 'ぼうか', 'phòng cháy');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '防水', 'ぼうすい', 'chống nước');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '伝統', 'でんとう', 'đèn điện');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '太陽光', 'たいようこう', 'ánh sáng mặt trời');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '示す', 'しめす', 'chỉ ra');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '目標', 'めじるし', '');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, '備えあれば憂いなし', 'そなえあればうれいなし', 'có chuẩn bị thì không lo');
INSERT INTO vocabularies (lesson_id, word, reading, meaning) VALUES (302, 'やさし', '', '');
